version: '3.9'
services:
  app:
    container_name: 'github-contribution-stats-app'
    tty: true
    stdin_open: true
    image: 'node:20-alpine'
    volumes:
      - '.:/app/'
    networks:
      - default
networks:
  default:
    name: 'github-contribution-stats_network'
