version: '3.4'
services:
  app:
    tty: true
    stdin_open: true
    image: 'node:10-alpine'
    volumes:
      - '.:/var/www/site/'
networks:
  default:
    external:
      name: '${DOCKER_HOST_PRE_DEFINED_NETWORK}'
